server:
  port: 8081 # Port du User Service

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service # Nom de la base
    username: root # Nom d'utilisateur
    password: admin # Mot de passe
  jpa:
    hibernate:
      ddl-auto: update # Mise à jour automatique des tables
    show-sql: true # Affiche les requêtes SQL dans la console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL du Eureka Server
