server:
  port: 8761 # Port du serveur Eureka

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Le serveur n'a pas besoin de s'enregistrer lui-même
    fetch-registry: false       # Il n'a pas besoin de récupérer le registre
  server:
    enable-self-preservation: false # (Optionnel) Pour les tests locaux
